# Generated by Django 5.0.4 on 2024-04-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_ui', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
